// AppDelegate.m — Boots the Mob BEAM on a background thread and presents
// a SwiftUI root view via UIHostingController (created by MobUIFactory).

#import <UIKit/UIKit.h>
#import <PhotosUI/PhotosUI.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#import <pthread.h>
#import <stdlib.h>
#import <string.h>
#include <erl_nif.h>
#include "mob_beam.h"
#import "MobApp-Swift.h"  // generated by swiftc; exposes MobUIFactory

// Declared in mob_nif — delivers {:push_token, :ios, token} to the registered screen process.
extern void mob_send_push_token(const char* hex_token);

// Code-generated by MobDev.Plugin.IOSBootstrap at build time — registers each
// activated plugin's SwiftUI view with MobNativeViewRegistry.shared. Defined
// via Swift's @_cdecl in the generated file so it's a plain C symbol; safe to
// call before mob_init_ui() even when no plugins are activated (the function
// body is just empty in that case).
extern void mob_register_plugins(void);

// Exported by mob_nif: the orientation mask set by Mob.Device.lock_orientation/1
// (UIInterfaceOrientationMaskAll when unlocked).
extern UIInterfaceOrientationMask mob_locked_orientation_mask(void);

static void* beam_thread(void* arg) {
    mob_start_beam((const char*)arg);
    return NULL;
}

static void bnana_configure_widget_storage(void) {
    NSURL* directory = [[NSFileManager defaultManager]
        containerURLForSecurityApplicationGroupIdentifier:@"group.com.aayushmau5.bnana"];

    if (directory) {
        setenv("BNANA_WIDGET_DIR", directory.fileSystemRepresentation, 1);
        [BnanaWidgetReloader watchDirectory:directory.path];
    }
}

static BOOL bnana_store_capture_url(NSURL* incomingURL) {
    NSURLComponents* incoming = [NSURLComponents componentsWithURL:incomingURL
                                           resolvingAgainstBaseURL:NO];
    if (![incoming.scheme.lowercaseString isEqualToString:@"bnana"] ||
        ![incoming.host.lowercaseString isEqualToString:@"capture"]) {
        return NO;
    }

    NSString* captured = nil;
    for (NSURLQueryItem* item in incoming.queryItems) {
        if ([item.name isEqualToString:@"url"]) {
            captured = item.value;
            break;
        }
    }

    NSURL* url = captured ? [NSURL URLWithString:captured] : nil;
    NSString* scheme = url.scheme.lowercaseString;
    if (captured.length == 0 || captured.length > 16384 ||
        !([scheme isEqualToString:@"http"] || [scheme isEqualToString:@"https"]) ||
        url.host.length == 0) {
        return NO;
    }

    NSArray<NSString*>* paths =
        NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
    NSString* directory = paths.firstObject;
    if (!directory) return NO;

    NSError* error = nil;
    [[NSFileManager defaultManager] createDirectoryAtPath:directory
                              withIntermediateDirectories:YES
                                               attributes:nil
                                                    error:&error];
    if (error) {
        NSLog(@"[Bnana] Could not create capture directory: %@", error);
        return NO;
    }

    NSString* path = [directory stringByAppendingPathComponent:@".pending_capture_url"];
    if (![captured writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:&error]) {
        NSLog(@"[Bnana] Could not store captured URL: %@", error);
        return NO;
    }

    return YES;
}

static UIViewController* bnana_root_view_controller(void) {
    for (UIScene* scene in UIApplication.sharedApplication.connectedScenes) {
        if ([scene isKindOfClass:UIWindowScene.class]) {
            UIWindowScene* windowScene = (UIWindowScene*)scene;
            UIWindow* window = windowScene.keyWindow ?: windowScene.windows.firstObject;
            if (window.rootViewController) return window.rootViewController;
        }
    }
    return nil;
}

static void bnana_send_photos_status(ErlNifPid pid, const char* status) {
    ErlNifEnv* env = enif_alloc_env();
    ERL_NIF_TERM message = enif_make_tuple2(
        env,
        enif_make_atom(env, "photos"),
        enif_make_atom(env, status)
    );
    enif_send(NULL, &pid, env, message);
    enif_free_env(env);
}

static void bnana_send_photo_error(ErlNifPid pid, const char* reason) {
    ErlNifEnv* env = enif_alloc_env();
    ERL_NIF_TERM message = enif_make_tuple3(
        env,
        enif_make_atom(env, "photos"),
        enif_make_atom(env, "error"),
        enif_make_atom(env, reason)
    );
    enif_send(NULL, &pid, env, message);
    enif_free_env(env);
}

static void bnana_send_picked_photo(ErlNifPid pid, NSString* path, long long size) {
    ErlNifEnv* env = enif_alloc_env();
    const char* pathBytes = path.UTF8String;
    const char* nameBytes = path.lastPathComponent.UTF8String;
    ErlNifBinary pathBinary;
    ErlNifBinary nameBinary;

    if (!enif_alloc_binary(strlen(pathBytes), &pathBinary)) {
        enif_free_env(env);
        bnana_send_photo_error(pid, "out_of_memory");
        return;
    }

    if (!enif_alloc_binary(strlen(nameBytes), &nameBinary)) {
        enif_release_binary(&pathBinary);
        enif_free_env(env);
        bnana_send_photo_error(pid, "out_of_memory");
        return;
    }

    memcpy(pathBinary.data, pathBytes, strlen(pathBytes));
    memcpy(nameBinary.data, nameBytes, strlen(nameBytes));

    ERL_NIF_TERM keys[3] = {
        enif_make_atom(env, "path"),
        enif_make_atom(env, "name"),
        enif_make_atom(env, "size")
    };
    ERL_NIF_TERM values[3] = {
        enif_make_binary(env, &pathBinary),
        enif_make_binary(env, &nameBinary),
        enif_make_int64(env, size)
    };
    ERL_NIF_TERM item;
    enif_make_map_from_arrays(env, keys, values, 3, &item);
    ERL_NIF_TERM items = enif_make_list1(env, item);
    ERL_NIF_TERM message = enif_make_tuple3(
        env,
        enif_make_atom(env, "photos"),
        enif_make_atom(env, "picked"),
        items
    );

    enif_send(NULL, &pid, env, message);
    enif_free_env(env);
}

@interface BnanaPhotoPickerDelegate : NSObject <PHPickerViewControllerDelegate>
@property(nonatomic) ErlNifPid pid;
@end

static BnanaPhotoPickerDelegate* g_bnana_photo_picker_delegate = nil;

@implementation BnanaPhotoPickerDelegate

- (void)picker:(PHPickerViewController*)picker
    didFinishPicking:(NSArray<PHPickerResult*>*)results {
    [picker dismissViewControllerAnimated:YES completion:nil];
    ErlNifPid pid = self.pid;
    g_bnana_photo_picker_delegate = nil;

    PHPickerResult* result = results.firstObject;
    if (!result) {
        bnana_send_photos_status(pid, "cancelled");
        return;
    }

    NSItemProvider* provider = result.itemProvider;
    [provider loadFileRepresentationForTypeIdentifier:UTTypeImage.identifier
                                   completionHandler:^(NSURL* url, NSError* error) {
        @autoreleasepool {
            if (!url || error) {
                bnana_send_photo_error(pid, "load_failed");
                return;
            }

            NSString* extension = url.pathExtension.lowercaseString;
            if (extension.length == 0) extension = @"jpg";
            NSString* filename = [NSString stringWithFormat:@"bnana_photo_%@.%@",
                                                             NSUUID.UUID.UUIDString,
                                                             extension];
            NSString* destination = [NSTemporaryDirectory() stringByAppendingPathComponent:filename];
            NSError* copyError = nil;

            if (![[NSFileManager defaultManager] copyItemAtPath:url.path
                                                         toPath:destination
                                                          error:&copyError]) {
                bnana_send_photo_error(pid, "copy_failed");
                return;
            }

            NSDictionary* attributes = [[NSFileManager defaultManager]
                attributesOfItemAtPath:destination
                                 error:&copyError];
            if (!attributes || copyError) {
                [[NSFileManager defaultManager] removeItemAtPath:destination error:nil];
                bnana_send_photo_error(pid, "copy_failed");
                return;
            }

            bnana_send_picked_photo(pid, destination, [attributes[NSFileSize] longLongValue]);
        }
    }];
}

@end

void bnana_present_photo_picker(ErlNifPid pid) {
    dispatch_async(dispatch_get_main_queue(), ^{
        UIViewController* root = bnana_root_view_controller();
        if (!root || root.presentedViewController || g_bnana_photo_picker_delegate) {
            bnana_send_photo_error(pid, "not_available");
            return;
        }

        PHPickerConfiguration* configuration = [[PHPickerConfiguration alloc] init];
        configuration.filter = PHPickerFilter.imagesFilter;
        configuration.selectionLimit = 1;
        configuration.preferredAssetRepresentationMode = PHPickerConfigurationAssetRepresentationModeCompatible;

        PHPickerViewController* picker =
            [[PHPickerViewController alloc] initWithConfiguration:configuration];
        g_bnana_photo_picker_delegate = [[BnanaPhotoPickerDelegate alloc] init];
        g_bnana_photo_picker_delegate.pid = pid;
        picker.delegate = g_bnana_photo_picker_delegate;
        [root presentViewController:picker animated:YES completion:nil];
    });
}

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)app
    didFinishLaunchingWithOptions:(NSDictionary*)opts {

    NSURL* launchURL = opts[UIApplicationLaunchOptionsURLKey];
    if (launchURL) bnana_store_capture_url(launchURL);
    bnana_configure_widget_storage();

    self.window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];

    UIViewController* vc = [MobUIFactory makeRootViewController];
    self.window.rootViewController = vc;
    [self.window makeKeyAndVisible];

    // Must run before mob_init_ui() so the registry has every plugin view
    // factory in place by the time the BEAM mounts its first screen.
    mob_register_plugins();

    mob_init_ui();

    extern const char* mob_app_module(void);
    pthread_t t;
    pthread_create(&t, NULL, beam_thread, (void*)mob_app_module());
    pthread_detach(t);

    return YES;
}

- (BOOL)application:(UIApplication*)app
            openURL:(NSURL*)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id>*)options {
    return bnana_store_capture_url(url);
}

// Holds an orientation lock. UIKit consults this window-level method in
// preference to the root view controller's -supportedInterfaceOrientations, so
// the rotation Mob.Device.lock_orientation/1 requests via requestGeometryUpdate
// actually sticks (and unlock_orientation/0 returns ...MaskAll = follow sensor).
- (UIInterfaceOrientationMask)application:(UIApplication*)app
    supportedInterfaceOrientationsForWindow:(UIWindow*)window {
    return mob_locked_orientation_mask();
}

- (void)application:(UIApplication*)app
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken {
    // Convert token bytes to hex string and deliver to Elixir via NIF.
    NSMutableString* hex = [NSMutableString stringWithCapacity:deviceToken.length * 2];
    const unsigned char* bytes = (const unsigned char*)deviceToken.bytes;
    for (NSUInteger i = 0; i < deviceToken.length; i++) {
        [hex appendFormat:@"%02x", bytes[i]];
    }
    mob_send_push_token([hex UTF8String]);
}

- (void)application:(UIApplication*)app
    didFailToRegisterForRemoteNotificationsWithError:(NSError*)error {
    NSLog(@"[Mob] Failed to register for remote notifications: %@", error);
}

@end

int main(int argc, char* argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"AppDelegate");
    }
}
